#!/bin/sh -ex
# Provide our own pg_dumpall

# Environment variables from env aren't available
export SNAP=/snap/all-dev-immich/current
export SNAP_COMMON=/var/snap/all-dev-immich/common

# _arch modified at build-time
export LD_LIBRARY_PATH="${SNAP}/usr/lib/_arch:${LD_LIBRARY_PATH}"
export PATH="${SNAP}/usr/lib/postgresql/16/bin:${PATH}"
# TBD user-changeable
# _pgdata="$(snapctl get postgresql.pgdata)"
export PGDATA="${SNAP_COMMON}/postgresql/database"

export LC_ALL="C"
export LC_CTYPE="C"

# We're fine with element splitting
# shellcheck disable=2068
exec "${SNAP}/usr/lib/postgresql/16/bin/pg_dumpall" $@
