name: all-dev-immich

adopt-info: immich

base: core24

grade: stable
confinement: strict
compression: lzo

icon: snap/gui/icon.png

license: "CC-BY-NC-SA-4.0 AND AGPL-3.0"

website: https://github.com/Half-Silver/all-dev-immich
source-code: https://github.com/Half-Silver/all-dev-immich
issues: https://github.com/Half-Silver/all-dev-immich/issues
contact: https://github.com/Half-Silver

summary: High performance self-hosted photo and video management solution.

description: |
  Immich is a high performance self-hosted photo and video management solution.

  This snap is optimized for Ubuntu Core. FFmpeg, Redis, and PostgreSQL are bundled.

  The snap is intended to work seamlessly with:
    - caddy

  Immich will expose itself on port 3001 by default and can be accessed
  locally or through reverse proxies.

assumes:
  - snapd2.68

package-repositories:
  - type: apt
    key-id: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    url: https://apt.postgresql.org/pub/repos/apt
    suites: [noble-pgdg]
    components: [main]

platforms:
  amd64:
  arm64:

lint:
  ignore:
    - library

system-usernames:
  _daemon_: shared

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts

  /etc/ImageMagick-6:
    symlink: $SNAP/etc/ImageMagick-6

  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6.9.11:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6.9.11

  /usr/lib/postgresql:
    bind: $SNAP/usr/lib/postgresql

  /usr/share/postgresql:
    bind: $SNAP/usr/share/postgresql

apps:
  redis:
    command: usr/bin/redis.sh

    daemon: simple
    install-mode: enable

    restart-condition: always

    plugs:
      - network
      - network-bind

  server:
    after:
      - postgresql
      - redis
      - createdb

    command: usr/bin/immich-server.sh

    daemon: simple
    install-mode: enable

    restart-condition: always

    plugs:
      - network
      - network-bind
      - mount-observe
      - opengl
      - removable-media

    environment:
      DB_PORT: "5433"
      DB_HOSTNAME: 127.0.0.1
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich

      REDIS_PORT: "6379"
      REDIS_HOSTNAME: 127.0.0.1

      NODE_ENV: production
      IMMICH_ENV: production

      IMMICH_BUILD_DATA: ${SNAP}/usr/lib/immich/build

      PATH: ${SNAP}/usr/lib/postgresql/16/bin:${PATH}

      PERL5LIB: ${SNAP}/usr/share/perl5:${SNAP}/usr/share/perl:${PERL5LIB}

  postgresql:
    command: usr/bin/postgresql.sh start

    daemon: simple
    install-mode: enable

    stop-command: usr/bin/postgresql.sh stop
    reload-command: usr/bin/postgresql.sh reload

    restart-condition: always

    plugs: &_pgplugs
      - network
      - network-bind

    environment: &_pgenv
      PGDATA: ${SNAP_COMMON}/postgresql/database
      PGPASSFILE: ${SNAP_COMMON}/postgresql/.pgpass

      PATH: ${SNAP}/usr/lib/postgresql/16/bin:${PATH}

  createdb:
    after:
      - postgresql

    command: usr/bin/postgresql.sh createdb

    daemon: oneshot
    install-mode: enable

    plugs: *_pgplugs

    environment: *_pgenv

  ml:
    after:
      - createdb

    command: usr/bin/machine-learning.sh

    daemon: simple
    install-mode: enable

    restart-condition: always

    plugs:
      - network
      - network-bind
      - opengl

    environment:
      LD_PRELOAD: "${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libmimalloc.so.2"

      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"

      NODE_ENV: production

      IMMICH_BUILD_DATA: "$SNAP/usr/lib/immich/build"

      TRANSFORMERS_CACHE: ${SNAP_COMMON}/cache

parts:
  immich:
    plugin: python

    source: https://github.com/immich-app/immich
    source-type: git
    source-depth: 1
    source-tag: v2.5.6

    build-snaps:
      - node/22/stable

    stage-snaps:
      - node/22/stable

    build-packages:
      - python3
      - python3-dev

      - libcfitsio-dev
      - libexif-dev
      - libexpat1-dev
      - libfftw3-dev
      - libglib2.0-dev
      - libgsf-1-dev
      - libheif-dev
      - libimagequant-dev
      - libjpeg-turbo8-dev
      - liblcms2-dev
      - libmatio-dev
      - libopenexr-dev
      - libopenjp2-7-dev
      - libopenslide-dev
      - liborc-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libtiff5-dev
      - libvips-dev
      - libwebp-dev

    stage-packages:
      - python3:${CRAFT_ARCH_BUILD_FOR}
      - libstdc++6:${CRAFT_ARCH_BUILD_FOR}
      - libvips42:${CRAFT_ARCH_BUILD_FOR}
      - perl:${CRAFT_ARCH_BUILD_FOR}
      - ffmpeg:${CRAFT_ARCH_BUILD_FOR}
      - redis-server:${CRAFT_ARCH_BUILD_FOR}

    build-environment:
      - COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      - NODE_OPTIONS: --max-old-space-size=4096
      - SHARPIGNORE_GLOBAL_LIBVIPS: "true"
      - CI: "1"

    override-pull: |
      craftctl default

      patch -p1 < "${CRAFT_PROJECT_DIR}/patches/pgdump.patch"

      rm -f cli/LICENSE

      craftctl set version=$(git describe --tags)

      npm install --global corepack@latest --force

      corepack enable pnpm

      pnpm fetch \
        --ignore-scripts

      pnpm install \
        --offline \
        --filter immich \
        --frozen-lockfile

      _sharp_dir="$(pnpm patch sharp | sed -n '3p' | sed 's/^[[:space:]]*//')"

      cd "${_sharp_dir}"

      sed -i 's/|| npm run build",/|| pnpm run build",/' package.json

      cd -

      pnpm patch-commit "${_sharp_dir}"

      cd "${CRAFT_PART_SRC}/web"

      pnpm add 'three@^0.179.0'

    override-build: |
      install -Dm644 LICENSE \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/app/LICENSE"

      mkdir -p \
        "${CRAFT_PART_INSTALL}/usr/bin" \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/cli" \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build" \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/app/server"

      cd "${CRAFT_PART_BUILD}/server"

      pnpm exec nest build \
        --type-check

      pnpm \
        --filter immich \
        --frozen-lockfile \
        build

      pnpm \
        --prod \
        --filter immich \
        --frozen-lockfile \
        --no-optional \
        deploy \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/app/server"

      cd -

      pnpm \
        --filter @immich/sdk \
        --filter immich-web \
        --frozen-lockfile install

      pnpm \
        --filter @immich/sdk \
        --filter immich-web build

      mkdir -p \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build"

      cp -af \
        "${CRAFT_PART_BUILD}/web/build" \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/www"

      install -Dm644 \
        "${CRAFT_PART_SRC}/plugins/manifest.json" \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/corePlugin/manifest.json"

    stage:
      - -usr/lib/immich/app/server/bin
      - -usr/lib/immich/app/server/test
      - -usr/lib/immich/app/server/.nvmrc
      - -usr/lib/immich/app/server/Dockerfile
      - -usr/lib/immich/app/server/.prettierrc
      - -usr/lib/immich/app/server/nest-cli.json
      - -usr/lib/immich/app/server/pnpm-lock.yaml
      - -usr/lib/immich/app/server/.prettierignore

  machine-learning:
    plugin: uv

    source: https://github.com/immich-app/immich
    source-type: git
    source-depth: 1
    source-tag: v2.5.6

    source-subdir: machine-learning

    uv-extras:
      - cpu

    build-snaps:
      - astral-uv

    build-environment:
      - UV_PYTHON: python3

    stage-packages:
      - gunicorn:all
      - libgl1:${CRAFT_ARCH_BUILD_FOR}
      - libmimalloc2.0:${CRAFT_ARCH_BUILD_FOR}

    override-build: |
      craftctl default

      mkdir -p "${CRAFT_PART_INSTALL}/etc"

      cp -rf \
        machine-learning/immich_ml/log_conf.json \
        "${CRAFT_PART_INSTALL}/etc"

    override-stage: |
      craftctl default

      unlink "${CRAFT_STAGE}/bin/python"

      ln -sf python3 "${CRAFT_STAGE}/bin/python"

  build-lock:
    after:
      - immich

    plugin: nil

    source: https://github.com/immich-app/base-images
    source-type: git
    source-depth: 1

    build-packages:
      - jq

    override-prime: |
      jq -s '.' "${CRAFT_PART_SRC}/server/sources/"*.json > /tmp/sources.json

      jq -s '.' "${CRAFT_PART_SRC}/server/packages/"*.json > /tmp/packages.json

      jq -n \
        --slurpfile sources /tmp/sources.json \
        --slurpfile packages /tmp/packages.json \
        '{sources: $sources[0], packages: $packages[0]}' \
        > "${CRAFT_PRIME}/usr/lib/immich/build/build-lock.json"

      chmod 644 \
        "${CRAFT_PRIME}/usr/lib/immich/build/build-lock.json"

  geonames:
    plugin: nil

    source: https://download.geonames.org/export/dump/cities500.zip

    build-packages:
      - curl

    override-pull: |
      craftctl default

      mkdir -p \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/geodata"

      curl -o \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/geodata/admin1CodesASCII.txt" \
        https://download.geonames.org/export/dump/admin1CodesASCII.txt

      curl -o \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/geodata/admin2Codes.txt" \
        https://download.geonames.org/export/dump/admin2Codes.txt

      curl -o \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/geodata/ne_10m_admin_0_countries.geojson" \
        https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_10m_admin_0_countries.geojson

      cp -f \
        "${CRAFT_PART_SRC}/"* \
        "${CRAFT_PART_INSTALL}/usr/lib/immich/build/geodata"

      date --iso-8601=seconds | tr -d "\n" \
        > "${CRAFT_PART_INSTALL}/usr/lib/immich/build/geodata/geodata-date.txt"

  postgresql:
    plugin: nil

    stage-packages:
      - postgresql-16:${CRAFT_ARCH_BUILD_FOR}
      - postgresql-client-16:${CRAFT_ARCH_BUILD_FOR}
      - postgresql-16-pgvector:${CRAFT_ARCH_BUILD_FOR}

    stage:
      - -usr/bin/pg_dump
      - -usr/bin/pg_dumpall

  vchord:
    plugin: nil

    build-packages:
      - curl

    # Update _ver to match the version in immich-app/base-images
    override-build: |
      _ver="0.3.0"
      _arch=$(dpkg --print-architecture)
      _deb="postgresql-16-vchord_${_ver}-1_${_arch}.deb"
      curl -fsSL -o "/tmp/${_deb}" \
        "https://github.com/tensorchord/VectorChord/releases/download/${_ver}/${_deb}"
      dpkg-deb -x "/tmp/${_deb}" "${CRAFT_PART_INSTALL}"

  scripts:
    after:
      - build-lock
      - geonames
      - immich
      - machine-learning
      - postgresql
      - vchord

    plugin: dump

    source: src/

    override-build: |
      craftctl default

      sed -i \
        "s/_arch/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/" \
        "${CRAFT_PART_INSTALL}/pg_dumpall"

    organize:
      "*": usr/bin/

    stage:
      - -usr/bin/graphics-core22-wrapper
      - -usr/bin/gpu-2404-wrapper

    override-prime: |
      craftctl default

      rm -f "${CRAFT_PRIME}/qemu_bcrypt."*